const arrayOfNames: Array<[number, string, string, string]> = [
  [1, ' 	ٱلرَّحْمَٰنُ', ' 	Ar-Rahmaan', ' 	The Most or Entirely Merciful'],
  [2, ' 	ٱلرَّحِيمُ', ' 	Ar-Raheem', ' 	The Bestower of Mercy'],
  [3, ' 	ٱلْمَلِكُ', ' 	Al-Malik', ' 	The King and Owner of Dominion'],
  [4, ' 	ٱلْقُدُّوسُ', ' 	Al-Quddus', ' 	The Absolutely Pure'],
  [5, ' 	ٱلسَّلَامُ', ' 	As-Salaam', ' 	The Perfection and Giver of Peace'],
  [6, ' 	ٱلْمُؤْمِنُ', ' 	Al-Mu’min', ' 	The One Who gives Emaan and Security'],
  [7, ' 	ٱلْمُهَيْمِنُ', ' 	Al-Muhaymin', ' 	The Guardian, The Witness, The Overseer'],
  [8, ' 	ٱلْعَزِيزُ', ' 	Al-Azeez', ' 	The All Mighty'],
  [9, ' 	ٱلْجَبَّارُ', ' 	Al-Jabbaar', ' 	The Compeller, The Restorer'],
  [10, ' 	ٱلْمُتَكَبِّرُ', ' 	Al-Mutakabbir', ' 	The Supreme, The Majestic'],
  [11, ' 	ٱلْخَٰلِقُ', ' 	Al-Khaaliq', ' 	The Creator, The Maker'],
  [12, ' 	ٱلْبَارِئُ', ' 	Al-Baari’', ' 	The Originator'],
  [13, ' 	ٱلْمُصَوِّرُ', ' 	Al-Musawwir', ' 	The Fashioner'],
  [14, ' 	ٱلْغَفَّارُ', ' 	Al-Ghaffaar', ' 	The All- and Oft-Forgiving'],
  [15, ' 	ٱلْقَهَّارُ', ' 	Al-Qahhaar', ' 	The Subduer, The Ever-Dominating'],
  [16, ' 	ٱلْوَهَّابُ', ' 	Al-Wahhaab', ' 	The Giver of Gifts'],
  [17, ' 	ٱلْرَّزَّاقُ', ' 	Ar-Razzaaq', ' 	The Provider'],
  [18, ' 	ٱلْفَتَّاحُ', ' 	Al-Fattah', ' 	The Opener, The Judge'],
  [19, ' 	ٱلْعَلِيمُ', ' 	Al-‘Aleem', ' 	The All-Knowing, The Omniscient'],
  [20, ' 	ٱلْقَابِضُ', ' 	Al-Qaabid', ' 	The Withholder'],
  [21, ' 	ٱلْبَاسِطُ', ' 	Al-Baasit', ' 	The Extender'],
  [22, ' 	ٱلْخَافِضُ', ' 	Al-Khaafidh', ' 	The Reducer, The Abaser'],
  [23, ' 	ٱلْرَّافِعُ', ' 	Ar-Raafi’', ' 	The Exalter, The Elevator'],
  [24, ' 	ٱلْمُعِزُّ', ' 	Al-Mu’izz', ' 	The Honourer, The Bestower'],
  [25, ' 	ٱلْمُذِلُّ', ' 	Al-Muzil', ' 	The Dishonourer, The Humiliator'],
  [26, ' 	ٱلسَّمِيعُ', ' 	As-Samee’', ' 	The All-Hearing'],
  [27, ' 	ٱلْبَصِيرُ', ' 	Al-Baseer', ' 	The All-Seeing'],
  [28, ' 	ٱلْحَكَمُ', ' 	Al-Hakam', ' 	The Judge, The Giver of Justice'],
  [29, ' 	ٱلْعَدْلُ', ' 	Al-‘Adl', ' 	The Utterly Just'],
  [30, ' 	ٱللَّطِيفُ', ' 	Al-Lateef', ' 	The Subtle One, The Most Gentle'],
  [31, ' 	ٱلْخَبِيرُ', ' 	Al-Khabeer', ' 	The Acquainted, The All-Aware'],
  [32, ' 	ٱلْحَلِيمُ', ' 	Al-Haleem', ' 	The Most Forbearing'],
  [33, ' 	ٱلْعَظِيمُ', ' 	Al-‘Azeem', ' 	The Magnificent, The Supreme'],
  [34, ' 	ٱلْغَفُورُ', ' 	Al-Ghafoor', ' 	The Forgiving, The Exceedingly Forgiving'],
  [35, ' 	ٱلشَّكُورُ', ' 	Ash-Shaakoor', ' 	The Most Appreciative'],
  [36, ' 	ٱلْعَلِيُّ', ' 	Al-‘Alee', ' 	The Most High, The Exalted'],
  [37, ' 	ٱلْكَبِيرُ', ' 	Al-Kabeer', ' 	The Greatest, The Most Grand'],
  [38, ' 	ٱلْحَفِيظُ', ' 	Al-Hafeedh', ' 	The Preserver, The All-Heedful and All-Protecting'],
  [39, ' 	ٱلْمُقيِتُ', ' 	Al-Muqeet', ' 	The Sustainer, The Maintainer'],
  [40, ' 	ٱلْحَسِيبُ', ' 	Al-Hasib', ' 	The Reckoner'],
  [41, ' 	ٱلْجَلِيلُ', ' 	Al-Jaleel', ' 	The Majestic'],
  [42, ' 	ٱلْكَرِيمُ', ' 	Al-Kareem', ' 	The Most Generous, The Most Esteemed'],
  [43, ' 	ٱلْرَّقِيبُ', ' 	Ar-Raqeeb', ' 	The Watchful, The All-Watchful'],
  [44, ' 	ٱلْمُجِيبُ', ' 	Al-Mujeeb', ' 	The Responsive, The Answerer'],
  [45, ' 	ٱلْوَاسِعُ', ' 	Al-Waasi’', ' 	The All-Encompassing, the Boundless'],
  [46, ' 	ٱلْحَكِيمُ', ' 	Al-Hakeem', ' 	The All-Wise'],
  [47, ' 	ٱلْوَدُودُ', ' 	Al-Wadud', ' 	The Most Loving'],
  [48, ' 	ٱلْمَجِيدُ', ' 	Al-Majeed', ' 	The Glorious, The Most Honorable'],
  [49, ' 	ٱلْبَاعِثُ', ' 	Al-Baa’ith', ' 	The Infuser of New Life'],
  [50, ' 	ٱلْشَّهِيدُ', ' 	As-Shaheed', ' 	The All Observing Witnessing'],
  [51, ' 	ٱلْحَقُّ', ' 	Al-Haqq', ' 	The Absolute Truth'],
  [52, ' 	ٱلْوَكِيلُ', ' 	Al-Wakeel', ' 	The Trustee, The Disposer of Affairs'],
  [53, ' 	ٱلْقَوِيِيُ', ' 	Al-Qawiyy', ' 	The All-Strong'],
  [54, ' 	ٱلْمَتِينُ', ' 	Al-Mateen', ' 	The Firm, The Steadfast'],
  [55, ' 	ٱلْوَلِيُ', ' 	Al-Walee', ' 	The Protecting Associate'],
  [56, ' 	ٱلْحَمِيدُ', ' 	Al-Hameed', ' 	The Praiseworthy'],
  [57, ' 	ٱلْمُحْصِي', ' 	Al-Muhsee', ' 	The All-Enumerating, The Counter'],
  [58, ' 	ٱلْمُبْدِئُ', ' 	Al-Mubdi’', ' 	The Originator, The Initiator'],
  [59, ' 	ٱلْمُعِيدُ', ' 	Al-Mu’id', ' 	The Restorer, The Reinstater'],
  [60, ' 	ٱلْمُحْيِي', ' 	Al-Muhyee', ' 	The Giver of Life'],
  [61, ' 	ٱلْمُمِيتُ', ' 	Al-Mumeet', ' 	The Creator of Death'],
  [62, ' 	ٱلْحَيِّيُ', ' 	Al-Hayy', ' 	The Ever-Living'],
  [63, ' 	ٱلْقَيُّومُ', ' 	Al-Qayyoom', ' 	The Sustainer, The Self-Subsisting'],
  [64, ' 	ٱلْوَاجِدُ', ' 	Al-Waajid', ' 	The Perceiver'],
  [65, ' 	ٱلْمَاجِدُ', ' 	Al-Maajid', ' 	The Illustrious, The Magnificent'],
  [66, ' 	ٱلْوَاحِدُ', ' 	Al-Waahid', ' 	The One, The Indivisible'],
  [67, ' 	ٱلْأَحَدُ', ' 	Al-Ahad', ' 	The Unique, The Only One'],
  [68, ' 	ٱلصَّمَدُ', ' 	As-Samad', ' 	The Eternal, Satisfier of Needs'],
  [69, ' 	ٱلْقَادِرُ', ' 	Al-Qaadir', ' 	The Omnipotent'],
  [70, ' 	ٱلْمُقْتَدِرُ', ' 	Al-Muqtadir', ' 	The Powerful'],
  [71, ' 	ٱلْمُقَدِّمُ', ' 	Al-Muqaddim', ' 	The Expediter, The Promoter'],
  [72, ' 	ٱلْمُؤَخِّرُ', ' 	Al-Mu’akhkhir', ' 	The Delayer'],
  [73, ' 	ٱلْأوَّلُ', ' 	Al-Awwal', ' 	The First'],
  [74, ' 	ٱلْآخِرُ', ' 	Al-Aakhir', ' 	The Last, The Utmost'],
  [75, ' 	ٱلظَّٰهِرُ', ' 	Az-Zaahir', ' 	The Manifest, The All-Surpassing'],
  [76, ' 	ٱلْبَاطِنُ', ' 	Al-Baatin', ' 	The Hidden One, Knower of the Hidden'],
  [77, ' 	ٱلْوَالِي', ' 	Al-Waalee', ' 	The Sole Governor'],
  [78, ' 	ٱلْمُتَعَالِي', ' 	Al-Muta’ali', ' 	The Self Exalted'],
  [79, ' 	ٱلْبَرُّ', ' 	Al-Barr', ' 	The Source of All Goodness'],
  [80, ' 	ٱلتَّوَابُ', ' 	At-Tawwaab', ' 	The Ever-Pardoning'],
  [81, ' 	ٱلْمُنْتَقِمُ', ' 	Al-Muntaqim', ' 	The Avenger'],
  [82, ' 	ٱلْعَفُوُ', ' 	Al-‘Afuww', ' 	The Pardoner'],
  [83, ' 	ٱلْرَّؤُوفُ', ' 	Ar-Ra’ooof', ' 	The Most Kind'],
  [84, ' 	مَالِكُ', ' ٱلْمُلْكُ 	Maalik', '-al-Mulk 	Master of the Dominion, Owner of the Kingdom'],
  [85, 'ذُوالْجَلاَلِ وَالإكْرَامِ', 'Thul-Jalaali wal-Ikraam', 'Possessor of Glory and Honour'],
  [86, ' 	ٱلْمُقْسِطُ', ' 	Al-Muqsiṭ', ' 	The Just One'],
  [87, ' 	ٱلْجَامِعُ', ' 	Al-Jaami’', ' 	The Gatherer, the Uniter'],
  [88, ' 	ٱلْغَنيُّ', ' 	Al-Ghaniyy', ' 	The Self-Sufficient, The Wealthy'],
  [89, ' 	ٱلْمُغْنِيُ', ' 	Al-Mughniyy', ' 	The Enricher'],
  [90, ' 	ٱلْمَانِعُ', ' 	Al-Maani’', ' 	The Withholder'],
  [91, ' 	ٱلضَّٰرَ', ' 	Ad-Dhaarr', ' 	The Distresser'],
  [92, ' 	ٱلنَّافِعُ', ' 	An-Naafi’', ' 	The Propitious, The Benefactor'],
  [93, ' 	ٱلْنُورُ', ' 	An-Noor', ' 	The Light'],
  [94, ' 	ٱلْهَادِي', ' 	Al-Haadi', ' 	The Guide'],
  [95, ' 	ٱلْبَدِيعُ', ' 	Al-Badee’', ' 	The Incomparable Originator'],
  [96, ' 	ٱلْبَاقِي', ' 	Al-Baaqi', ' 	The Ever-Lasting'],
  [97, ' 	ٱلْوَارِثُ', ' 	Al-Waarith', ' 	The Inheritor'],
  [98, ' 	ٱلرَّشِيدُ', ' 	Ar-Rasheed', ' 	The Guide to the Right Path'],
  [99, ' 	ٱلصَّبُورُ', ' 	Al-Saboor', ' 	The Patient'],
];
export default arrayOfNames;
